env:
  CIRRUS_CLONE_DEPTH: 1

task:
  name: Build iyad aziez os
  timeout_in: 120m
  container:
    image: ubuntu:20.04
    cpu: 8
    memory: 24G

  setup_environment_script:
    - apt-get update && apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
    - mkdir -p ~/bin
    - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod a+x ~/bin/repo
    - export PATH="~/bin:$PATH"

  build_script:
    - export PATH="~/bin:$PATH"
    - repo init -u https://github.com/LineageOS/android.git -b lineage-16.0 --git-lfs --depth=1
    - mkdir -p .repo/local_manifests
    - curl -o .repo/local_manifests/gt58lte.xml https://raw.githubusercontent.com/$CIRRUS_REPO_FULL_NAME/main/.repo/local_manifests/gt58lte.xml
    - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
    - sed -i 's/PRODUCT_PROPERTY_OVERRIDES += \\/PRODUCT_PROPERTY_OVERRIDES += \\\\n    ro.modversion=iyad_aziez_os_9.0 \\\\n    ro.lineage.version=iyad_aziez_os_gt58lte \\\\n    /g' vendor/lineage/config/common.mk
    - export WITH_SU=true
    - source build/envsetup.sh
    - lunch lineage_gt58lte-userdebug
    - mka bacon -j8
